feat: support new wisp specifications
MercuryWorkshop/wisp-server-node pull request #7
Opened 2024-06-28 17:25 UTC by builtbyvys

this pull request supports the new [wisp specifications](https://github.com/MercuryWorkshop/wisp-protocol/tree/v2)

2024-06-28 17:27 UTC, builtbyvys commented
it is important to note that auth isn't fully supported yet at this time

2024-06-29 08:51 UTC, ading2210 commented
Why did you change the indentation on every single file from 4 to 2 spaces?

2024-06-29 08:51 UTC, ading2210 requested changes
Please fix the indentation.

2024-06-29 08:52 UTC, ading2210 commented
Also Wisp v2 isn't official yet, so there's no point merging this right now.

2024-06-29 12:11 UTC, builtbyvys commented
> Why did you change the indentation on every single file from 4 to 2 spaces?

sorry, I think I forgot to relint before pushing the commit

2024-06-29 12:11 UTC, builtbyvys commented
> Please fix the indentation.

will do when I have the time later today

2024-07-25 02:08 UTC, builtbyvys reviewed
issue with the "pretty" script that'd fail to run due to LICENSE not being ignored (as there's no .prettierignore)

2025-02-02 01:36 UTC, closed without merging